from django.db import models

# Create your models here.

REGIONES = (
        ('I de Tarapaca','I de Tarapaca'),
        ('II de Antofagasta', 'II de Antofagasta'),
        ('III de Atacama','III de Atacama'),
        ('IV de Coquimbo','IV de Coquimbo'),
        ('V de Valparaiso','V de Valparaiso'),
        ('VI del Libertador General Bernardo OHiggins','VI del Libertador General Bernardo OHiggins'),
        ('VII del Maule','VII del Maule'),
        ('VIII de Concepcion','VIII de Concepcion'),
        ('IX de la Araucania','IX de la Araucania'),
        ('X de Los Lagos','X de Los Lagos'),
        ('XI de Aysen del General Carlos IbaNez del Campo','XI de Aysen del General Carlos IbaNez del Campo'),
        ('XII de Magallanes y de la Antartica Chilena','XII de Magallanes y de la Antartica Chilena'),
        ('XIII Metropolitana de Santiago','XIII Metropolitana de Santiago'),
        ('XIV de Los Rios','XIV de Los Rios'),
        ('XV de Arica y Parinacota','XV de Arica y Parinacota'),
        ('XVI del Nuble','XVI del Nuble'),
    )

CIUDAD = (
        # Arica y Parinacota
        ('ARICA','ARICA'),
        ('CAMARONES','CAMARONES'),
        ('PUTRE','PUTRE'),
        ('GENERAL LAGOS','GENERAL LAGOS'),

        # TarapacA
        ('IQUIQUE','IQUIQUE'),
        ('ALTO HOSPICIO','ALTO HOSPICIO'),
        ('POZO ALMONTE','POZO ALMONTE'),
        ('CAMINA','CAMINA'),
        ('COLCHANE','COLCHANE'),
        ('HUARA','HUARA'),
        ('PICA','PICA'),

        # Antofagasta
        ('ANTOFAGASTA','ANTOFAGASTA'),
        ('MEJILLONES','MEJILLONES'),
        ('SIERRA GORDA','SIERRA GORDA'),
        ('TALTAL','TALTAL'),
        ('CALAMA','CALAMA'),
        ('OLLAGUE','OLLAGUE'),
        ('SAN PEDRO DE ATACAMA','SAN PEDRO DE ATACAMA'),
        ('TOCOPILLA','TOCOPILLA'),
        ('MARIA ELENA','MARIA ELENA'),

        # ATACAMA
        ('COPIAPO','COPIAPO'),
        ('CALDERA','CALDERA'),
        ('TIERRA AMARILLA','TIERRA AMARILLA'),
        ('CHANARAL','CHANARAL'),
        ('DIEGO DE ALMAGRO','DIEGO DE ALMAGRO'),
        ('VALLENAR','VALLENAR'),
        ('ALTO DEL CARMEN','ALTO DEL CARMEN'),
        ('FREIRINA','FREIRINA'),
        ('HUASCO','HUASCO'),

        # COQUIMBO
        ('LA SERENA','LA SERENA'),
        ('COQUIMBO','COQUIMBO'),
        ('ANDACOLLO','ANDACOLLO'),
        ('LA HIGUERA','LA HIGUERA'),
        ('PAIGUANO','PAIGUANO'),
        ('VICUNA','VICUNA'),
        ('ILLAPEL','ILLAPEL'),
        ('CANELA','CANELA'),
        ('LOS VILOS','LOS VILOS'),
        ('SALAMANCA','SALAMANCA'),
        ('OVALLE','OVALLE'),
        ('COMBARBALA','COMBARBALA'),
        ('MONTE PATRIA','MONTE PATRIA'),
        ('PUNITAQUI','PUNITAQUI'),
        ('RIO HURTADO','RIO HURTADO'),

        # VALPARAISO
        ('VALPARAISO','VALPARAISO'),
        ('CASABLANCA','CASABLANCA'),
        ('CONCON','CONCON'),
        ('JUAN FERNANDEZ','JUAN FERNANDEZ'),
        ('PUCHUNCAVI','PUCHUNCAVI'),
        ('QUINTERO','QUINTERO'),
        ('VINA DEL MAR','VINA DEL MAR'),
        ('ISLA DE PASCUA','ISLA DE PASCUA'),
        ('LOS ANDES','LOS ANDES'),
        ('CALLE LARGA','CALLE LARGA'),
        ('RINCONADA','RINCONADA'),
        ('SAN ESTEBAN','SAN ESTEBAN'),
        ('LA LIGUA','LA LIGUA'),
        ('CABILDO','CABILDO'),
        ('PAPUDO','PAPUDO'),
        ('PETORCA','PETORCA'),
        ('ZAPALLAR','ZAPALLAR'),
        ('QUILLOTA','QUILLOTA'),
        ('CALERA','CALERA'),
        ('HIJUELAS','HIJUELAS'),
        ('LA CRUZ','LA CRUZ'),
        ('NOGALES','NOGALES'),
        ('SAN ANTONIO','SAN ANTONIO'),
        ('ALGARROBO','ALGARROBO'),
        ('CARTAGENA','CARTAGENA'),
        ('EL QUISCO','EL QUISCO'),
        ('EL TABO','EL TABO'),
        ('SANTO DOMINGO','SANTO DOMINGO'),
        ('SAN FELIPE','SAN FELIPE'),
        ('CATEMU','CATEMU'),
        ('LLAILLAY','LLAILLAY'),
        ('PAQUEHUE','PANQUEHUE'),
        ('PUTAENDO','PUTAENDO'),
        ('SANTA MARIA','SANTA MARIA'),
        ('QUILPUE','QUILPUE'),
        ('LIMACHE','LIMACHE'),
        ('OLMUE','OLMUE'),
        ('VILLA ALEMANA','VILLA ALEMANA'),

        # LIBERTADOR BERNARDO O´HIGGINS
        ('RANCAGUA','RANCAGUA'),
        ('CODEGUA','CODEGUA'),
        ('COINCO','COINCO'),
        ('COLTAUCO','COLTAUCO'),
        ('DONIHUE','DONIHUE'),
        ('GRANEROS','GRANEROS'),
        ('LAS CABRAS','LAS CABRAS'),
        ('MACHALI','MACHALI'),
        ('MALLOA','MALLOA'),
        ('MOSTAZAL','MOSTAZAL'),
        ('OLIVAR','OLIVAR'),
        ('PEUMO','PEUMO'),
        ('PICHIDEGUA','PICHIDEGUA'),
        ('QUINTA DE TILCOCO','QUINTA DE TILCOCO'),
        ('RENGO','RENGO'),
        ('REQUINOA','REQUINOA'),
        ('SAN VICENTE','SAN VICENTE'),
        ('PICHILEMU','PICHILEMU'),
        ('LA ESTRELLA','LA ESTRELLA'),
        ('LITUECHE','LITUECHE'),
        ('MARCHIHUE','MARCHIHUE'),
        ('NAVIDAD','NAVIDAD'),
        ('PAREDONES','PAREDONES'),
        ('SAN FERNANDO','SAN FERNANDO'),
        ('CHEPICA','CHEPICA'),
        ('CHIMBARONGO','CHIMBARONGO'),
        ('LOLOL','LOLOL'),
        ('NANCAGUA','NANCAGUA'),
        ('PALMILLA','PALMILLA'),
        ('PERALILLO','PERALILLO'),
        ('PLACILLA','PLACILLA'),
        ('PUMANQUE','PUMANQUE'),
        ('SANTA CRUZ','SANTA CRUZ'),

        #MAULE
        ('TALCA','TALCA'),
        ('CONSTITUCION','CONSTITUCION'),
        ('CUREPTO','CUREPTO'),
        ('EMPEDRADO','EMPEDRADO'),
        ('MAULE','MAULE'),
        ('PELARCO','PELARCO'),
        ('PENCAHUE','PENCAHUE'),
        ('RIO CLARO','RIO CLARO'),
        ('SAN CLEMENTE','SAN CLEMENTE'),
        ('SAN RAFAEL','SAN RAFAEL'),
        ('CAUQUENES','CAUQUENES'),
        ('CHANCO','CHANCO'),
        ('PELLUHUE','PELLUHUE'),
        ('CURICO','CURICO'),
        ('HUALANE','HUALANE'),
        ('LINCANTEN','LINCANTEN'),
        ('MOLINA','MOLINA'),
        ('RAUCO','RAUCO'),
        ('ROMERAL','ROMERAL'),
        ('SAGRADA FAMILIA','SAGRADA FAMILIA'),
        ('TENO','TENO'),
        ('VICHUQUEN','VICHUQUEN'),
        ('LINARES','LINARES'),
        ('COLBUN','COLBUN'),
        ('LONGAVI','LONGAVI'),
        ('PARRAL','PARRAL'),
        ('RETIRO','RETIRO'),
        ('SAN JAVIER','SAN JAVIER'),
        ('VILLA ALEGRE','VILLA ALEGRE'),
        ('YERBAS BUENAS','YERBAS BUENAS'),

        # NUBLE
        ('COBQUECURA','COBQUECURA'),
        ('COELMU','COELMU'),
        ('NINHUE','NINHUE'),
        ('PORTEZUELO','PORTEZUELO'),
        ('QUIRIHUE','QUIRIHUE'),
        ('RANQUIL','RANQUIL'),
        ('TREGUACO','TREGUACO'),
        ('BULNES','BULNES'),
        ('CHILLAN VIEJO','CHILLAN VIEJO'),
        ('EL CARMEN','EL CARMEN'),
        ('PEMUCO','PEMUCO'),
        ('PINTO','PINTO'),
        ('QUILLON','QUILLON'),
        ('SAN IGNACIO','SAN IGNACIO'),
        ('YUNGAY','YUNGAY'),
        ('COIHUECO','COIHUECO'),
        ('NIQUEN','NIQUEN'),
        ('SAN CARLOS','SAN CARLOS'),
        ('SAN FABIAN','SAN FABIAN'),
        ('SAN NICOLAS','SAN NICOLAS'),

        # BIOBIO
        ('CONCEPCION','CONCEPCION'),
        ('CORONEL','CORONEL'),
        ('CHIGUAYANTE','CHIGUAYANTE'),
        ('FLORIDA','FLORIDA'),
        ('HUALQUI','HUALQUI'),
        ('LOTA','LOTA'),
        ('PENCO','PENCO'),
        ('SAN PEDRO DE LA PAZ','SAN PEDRO DE LA PAZ'),
        ('SANTA JUANA','SANTA JUANA'),
        ('TALCAHUANO','TALCAHUANO'),
        ('TOME','TOME'),
        ('HUALPEN','HUALPEN'),
        ('LEBU','LEBU'),
        ('ARAUCO','ARAUCO'),
        ('CANETE','CANETE'),
        ('CONTULMO','CONTULMO'),
        ('CURANILAHUE','CURANILAHUE'),
        ('LOS ALAMOS','LOS ALAMOS'),
        ('TIRUA','TIRUA'),
        ('LOS ANGELES','LOS ANGELES'),
        ('ANTUCO','ANTUCO'),
        ('CABRERO','CABRERO'),
        ('LAJA','LAJA'),
        ('MULCHEN','MULCHEN'),
        ('NACIMIENTO','NACIMIENTO'),
        ('NEGRETE','NEGRETE'),
        ('QUILACO','QUILACO'),
        ('QUILLECO','QUILLECO'),
        ('SAN ROSENDO','SAN ROSENDO'),
        ('SANTA BARBARA','SANTA BARBARA'),
        ('TUCAPEL','TUCAPEL'),
        ('YUMBEL','YUMBEL'),
        ('ALTO BIOBIO','ALTO BIOBIO'),

        # LA ARAUCANIA
        ('TEMUCO','TEMUCO'),
        ('CARAHUE','CARAHUE'),
        ('CUNCO','CUNCO'),
        ('CURARREHUE','CURARREHUE'),
        ('FREIRE','FREIRE'),
        ('GALVARINO','GALVARINO'),
        ('GORBEA','GORBEA'),
        ('LAUTARO','LAUTARO'),
        ('LONCOCHE','LONCOCHE'),
        ('MELIPEUCO','MELIPEUCO'),
        ('NUEVA IMPERIAL','NUEVA IMPERIAL'),
        ('PADRE LAS CASAS','PADRE LAS CASAS'),
        ('PERQUENCO','PERQUENCO'),
        ('PITRUFQUEN','PITRUFQUEN'),
        ('PUCON','PUCON'),
        ('SAAVEDRA','SAAVEDRA'),
        ('TEODORO SCHMIDT','TEODORO SCHMIDT'),
        ('TOLTEN','TOLTEN'),
        ('VILCUN','VILCUN'),
        ('VILLARICA','VILLARICA'),
        ('CHOLCHOL','CHOLCHOL'),
        ('ANGOL','ANGOL'),
        ('COLLIPULLI','COLLIPULLI'),
        ('CURACAUTIN','CURACAUTIN'),
        ('ERCILLA','ERCILLA'),
        ('LONQUIMAY','LONQUIMAY'),
        ('LOS SAUCES','LOS SAUCES'),
        ('LUMACO','LUMACO'),
        ('PUREN','PUREN'),
        ('RENAICO','RENAICO'),
        ('TRAIGUEN','TRAIGUEN'),
        ('VICTORIA','VICTORIA'),

        # LOS RIOS
        ('VALDIVIA','VALDIVIA'),
        ('CORRAL','CORRAL'),
        ('LANCO','LANCO'),
        ('LOS LAGOS','LOS LAGOS'),
        ('MAFIL','MAFIL'),
        ('MARIQUINA','MARAQUINA'),
        ('PAILLACO','PAILLACO'),
        ('PANQUIPULLI','PANGUIPULLI'),
        ('LA UNION','LA UNION'),
        ('FUTRONO','FUTRONO'),
        ('LAGO RANCO','LAGO RANCO'),
        ('RIO BUENO','RIO BUENO'),

        # LOS LAGOS
        ('PUERTO MONTT','PUERTO MONTT'),
        ('CALBUCO','CALBUCO'),
        ('COCHAMO','COCHAMO'),
        ('FRESIA','FRESIA'),
        ('FRUTILLAR','FRUTILLAR'),
        ('LOS MUERMOS','LOS MUERMOS'),
        ('LLANQUIHUE','LLANQUIHUE'),
        ('MAULLIN','MAULLIN'),
        ('PUERTO VARAS','PUERTO VARAS'),
        ('CASTRO','CASTRO'),
        ('ANCUD','ANCUD'),
        ('CHONCHI','CHONCHI'),
        ('CURACO DE VELEZ','CURACO DE VELEZ'),
        ('DALCAHUE','DALCAHUE'),
        ('PUQUELDON','PUQUELDON'),
        ('QUEILEN','QUEILEN'),
        ('QUELLON','QUELLON'),
        ('QUEMCHI','QUEMCHI'),
        ('QUINCHAO','QUINCHAO'),
        ('OSORNO','OSORNO'),
        ('PUERTO OCTAY','PUERTO OCTAY'),
        ('PURRANQUE','PURRANQUE'),
        ('PUYEHUE','PUYEHUE'),
        ('RIO NEGRO','RIO NEGRO'),
        ('SAN JUAN DE LA COSTA','SAN JUAN DE LA COSTA'),
        ('SAN PABLO','SAN PABLO'),
        ('CHAITEN','CHAITEN'),
        ('FUTALEUFU','FUTALEUFU'),
        ('HUALAIHUE','HUALAIHUE'),
        ('PALENA','PALENA'),

        # AYSEN
        ('COIHAIQUE','COIHAIQUE'),
        ('LAGO VERDE','LAGO VERDE'),
        ('AYSEN','AYSEN'),
        ('CISNES','CISNES'),
        ('GUAITECAS','GUAITECAS'),
        ('COCHRANE','COCHRANE'),
        ('OHIGGINS','OHIGGINS'),
        ('TORTEL','TORTEL'),
        ('CHILE CHICO','CHILE CHICO'),
        ('RIO IBANEZ','RIO IBANEZ'),

        # MAGALLANES Y ANTARTICA CHILENA
        ('PUNTA ARENAS','PUNTA ARENAS'),
        ('LAGUNA BLANCA','LAGUNA BLANCA'),
        ('RIO VERDE','RIO VERDE'),
        ('SAN GREGORIO','SAN GREGORIO'),
        ('CABO DE HORNOS (EX NAVARINO)','CABO DE HORNOS (EX NAVARINO)'),
        ('ANTARTICA','ANTARTICA'),
        ('PORVENIR','PORVENIR'),
        ('PRIMAVERA','PRIMAVERA'),
        ('TIMAUKEL','TIMAUKEL'),
        ('NATALES','NATALES'),
        ('TORRES DEL PAINE','TORRES DEL PAINE'),

        # METROPOLITANA DE SANTIAGO
        ('CERRILLOS','CERRILLOS'),
        ('CERRO NAVIA','CERRO NAVIA'),
        ('CONCHALI','CONCHALI'),
        ('EL BOSQUE','EL BOSQUE'),
        ('ESTACION CENTRAL','ESTACION CENTRAL'),
        ('HUECHURABA','HUECHURABA'),
        ('INDEPENDENCIA','INDEPENDENCIA'),
        ('LA CISTERNA','LA CISTERNA'),
        ('LA FLORIDA','LA FLORIDA'),
        ('LA GRANJA','LA GRANJA'),
        ('LA PINTANA','LA PINTANA'),
        ('LA REINA','LA REINA'),
        ('LAS CONDES','LAS CONDES'),
        ('LO BARNECHEA','LO BARNECHEA'),
        ('LO ESPEJO','LO ESPEJO'),
        ('LO PRADO','LO PRADO'),
        ('MACUL','MACUL'),
        ('MAIPU','MAIPU'),
        ('NUNOA','NUNOA'),
        ('PEDRO AGUIRRE CERDA','PEDRO AGUIRRE CERDA'),
        ('PENALOLEN','PENALOLEN'),
        ('PROVIDENCIA','PROVIDENCIA'),
        ('PUDAHUEL','PUDAHUEL'),
        ('QUILICURA','QUILICURA'),
        ('QUINTA NORMAL','QUINTA NORMAL'),
        ('RECOLETA','RECOLETA'),
        ('RENCA','RENCA'),
        ('SAN JOAQUIN','SAN JOAQUIN'),
        ('SAN MIGUEL','SAN MIGUEL'),
        ('SAN RAMON','SAN RAMON'),
        ('VITACURA','VITACURA'),
        ('PUENTE ALTO','PUENTE ALTO'),
        ('PIRQUE','PIRQUE'),
        ('SAN JOSE DE MAIPO','SAN JOSE DE MAIPO'),
        ('COLINA','COLINA'),
        ('LAMPA','LAMPA'),
        ('TILTIL','TILTIL'),
        ('SAN BERNARDO','SAN BERNARDO'),
        ('BUIN','BUIN'),
        ('CALERA DE TANGO','CALERA DE TANGO'),
        ('PAINE','PAINE'),
        ('MELIPILLA','MELIPILLA'),
        ('ALHUE','ALHUE'),
        ('CURACAVI','CURACAVI'),
        ('MARIA PINTO','MARIA PINTO'),
        ('SAN PEDRO','SAN PEDRO'),
        ('TALAGANTE','TALAGANTE'),
        ('EL MONTE','EL MONTE'),
        ('ISLA DE MAIPO','ISLA DE MAIPO'),
        ('PADRE HURTADO','PADRE HURTADO'),
        ('PENAFLOR','PENAFLOR'),
    )


TIPOVIVIENDA = (
        ('Casa Patio Grande','Casa Patio Grande'),
        ('Casa Patio PequeNo', 'Casa Patio PequeNo'),
        ('Casa Sin Patio','Casa Sin Patio'),
        ('Departamento','Departamento'),
    )


class Persona(models.Model):
    rut = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    telefono = models.CharField(max_length=9)
    region = models.CharField(max_length=100, choices=REGIONES)
    comuna = models.CharField(max_length=100, choices=CIUDAD)
    vivienda = models.CharField(max_length=100, choices=TIPOVIVIENDA)
    
    def __str__(self):
        return self.correo

    def __str__(self):
        return '{}'.format(self.nombre)


        

